<?php

namespace AppBundle\Repository;

/**
 * QualificationCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualificationCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
