parameters:
#    parameter_name: value

services:
    app.form.person:
        class: AppBundle\Form\PersonType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app.form.person }
