parameters:
#    parameter_name: value

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']



    AdminBundle\:
        resource: '../../src/AdminBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AdminBundle/{Entity,Repository}'

    AdminBundle\Controller\:
        resource: '../../src/AdminBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    app.form.person:
        class: AppBundle\Form\Type\PersonType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app.form.person }

    AppBundle\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }


    AppBundle\Form\Extension\HelpTextExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
