parameters:
#    parameter_name: value

services:
    app.form.person:
        class: AppBundle\Form\Type\PersonType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app.form.person }

    membership_service:
        class: AppBundle\Services\MembershipService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]
